### PR TITLE
EID-1089: Uplift Hub to Java 11

### PR DESCRIPTION
**Pull request by dbes-gds**
Uplift to Gradle 4.10.2 in verify-test-rp.
Include additional jars in the build script to avoid supplying --add-modules on startup for > Java 9.
Java 8 and 10 both supported.
Java 11 is not supported if tests need to run.
This change allows test-rp to start in Java 10 or 11 in order to test hub end-to-end.

### CODE REVIEW

**Comment by JHjava** [comment]
Travis seems to be complaining about not building on 10?

**Comment by JHjava** [comment]
Travis is complaining about not building on JDK10.

**Comment by dbes-gds** [comment]
Note that this PR doesn't enable running on java11, pre-commit will only run under java8 and java10.

**Comment by dbes-gds** [comment]
Superseeded by uplift to Gradle 5 which is already merged.

**Pull request closed without merging**
