### PR TITLE
Fix jar name

### PR DESCRIPTION
**Pull request by karlbaker02**
This commit fixes the name of the jar file produced by the build to be the new name of the repository, `verify-test-rp`.

### CODE REVIEW

**Comment by willp-bl** [comment]
If merged this will turn into a fun and interesting yak shave because we rely on the old jar name in various places.

**Comment by karlbaker02** [comment]
Running `hub-startup` in the acceptance tests on master results in test-rp failing to start-up without this change.

**Comment by karlbaker02** [comment]
@willp-bl @richardTowers What's the best way to proceed on this? Do we need to have more discussion or can this be merged?

**Comment by willp-bl** [comment]
It might not have been working because you could have had two jars in the build directory - try a `gradle clean` in verify-test-rp before running `hub-startup.sh`; see https://github.com/alphagov/verify-local-startup/blob/8825ebbbfb34303fa6488dd9e903eb9e995dd066/lib/services.sh#L49 for how the jars are started

I don't mind if this gets merged, but if the above suggestion doesn't work then you need to be aware that you need to pick a yak shave:

* don't merge this and fix the acceptance test startup
* merge this and fix the modestly sized fallout of changing the jar name

**Pull request closed without merging**
